networks:
  deploy-dev:
    driver: bridge
services:
#  logistic:
#    container_name: logistic
#    image: logistic
#    build:
#      context: .
#      dockerfile: WebApi/Dockerfile
#    environment:
#      ASPNETCORE_ENVIRONMENT: Production
#      ASPNETCORE_HTTP_PORTS: 8085
#    ports:
#      - "8085:8085"
#    networks:
#      - deploy-dev
#    depends_on:
#      - logistic-db
  logistic-db:
    container_name: logistic-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: logistic_db
      PGPORT: 5438
    ports:
      - "5438:5438"
    networks:
      - deploy-dev
    volumes:
      - .postgres-data:/data
volumes:
  postgres-data: